// Package elevenlabs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package elevenlabs

import (
	"encoding/json"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Defines values for ExtendedSubscriptionResponseModelCurrency.
const (
	ExtendedSubscriptionResponseModelCurrencyEur ExtendedSubscriptionResponseModelCurrency = "eur"
	ExtendedSubscriptionResponseModelCurrencyUsd ExtendedSubscriptionResponseModelCurrency = "usd"
)

// Defines values for ExtendedSubscriptionResponseModelStatus.
const (
	ExtendedSubscriptionResponseModelStatusActive            ExtendedSubscriptionResponseModelStatus = "active"
	ExtendedSubscriptionResponseModelStatusCanceled          ExtendedSubscriptionResponseModelStatus = "canceled"
	ExtendedSubscriptionResponseModelStatusFree              ExtendedSubscriptionResponseModelStatus = "free"
	ExtendedSubscriptionResponseModelStatusIncomplete        ExtendedSubscriptionResponseModelStatus = "incomplete"
	ExtendedSubscriptionResponseModelStatusIncompleteExpired ExtendedSubscriptionResponseModelStatus = "incomplete_expired"
	ExtendedSubscriptionResponseModelStatusPastDue           ExtendedSubscriptionResponseModelStatus = "past_due"
	ExtendedSubscriptionResponseModelStatusTrialing          ExtendedSubscriptionResponseModelStatus = "trialing"
	ExtendedSubscriptionResponseModelStatusUnpaid            ExtendedSubscriptionResponseModelStatus = "unpaid"
)

// Defines values for FineTuningResponseModelFinetuningState.
const (
	FineTuned    FineTuningResponseModelFinetuningState = "fine_tuned"
	IsFineTuning FineTuningResponseModelFinetuningState = "is_fine_tuning"
	NotStarted   FineTuningResponseModelFinetuningState = "not_started"
)

// Defines values for HistoryItemResponseModelState.
const (
	Created    HistoryItemResponseModelState = "created"
	Deleted    HistoryItemResponseModelState = "deleted"
	Processing HistoryItemResponseModelState = "processing"
)

// Defines values for SubscriptionResponseModelCurrency.
const (
	SubscriptionResponseModelCurrencyEur SubscriptionResponseModelCurrency = "eur"
	SubscriptionResponseModelCurrencyUsd SubscriptionResponseModelCurrency = "usd"
)

// Defines values for SubscriptionResponseModelStatus.
const (
	SubscriptionResponseModelStatusActive            SubscriptionResponseModelStatus = "active"
	SubscriptionResponseModelStatusCanceled          SubscriptionResponseModelStatus = "canceled"
	SubscriptionResponseModelStatusFree              SubscriptionResponseModelStatus = "free"
	SubscriptionResponseModelStatusIncomplete        SubscriptionResponseModelStatus = "incomplete"
	SubscriptionResponseModelStatusIncompleteExpired SubscriptionResponseModelStatus = "incomplete_expired"
	SubscriptionResponseModelStatusPastDue           SubscriptionResponseModelStatus = "past_due"
	SubscriptionResponseModelStatusTrialing          SubscriptionResponseModelStatus = "trialing"
	SubscriptionResponseModelStatusUnpaid            SubscriptionResponseModelStatus = "unpaid"
)

// AddVoiceResponseModel defines model for AddVoiceResponseModel.
type AddVoiceResponseModel struct {
	VoiceId string `json:"voice_id"`
}

// BodyAddVoiceV1VoicesAddPost defines model for Body_Add_voice_v1_voices_add_post.
type BodyAddVoiceV1VoicesAddPost struct {
	// Description How would you describe the voice?
	Description *string `json:"description,omitempty"`

	// Files One or more audio files to clone the voice from
	Files []openapi_types.File `json:"files"`

	// Labels Serialized labels dictionary for the voice.
	Labels *string `json:"labels,omitempty"`

	// Name The name that identifies this voice. This will be displayed in the dropdown of the website.
	Name string `json:"name"`
}

// BodyDownloadHistoryItemsV1HistoryDownloadPost defines model for Body_Download_history_items_v1_history_download_post.
type BodyDownloadHistoryItemsV1HistoryDownloadPost struct {
	// HistoryItemIds A list of history items to download, you can get IDs of history items and other metadata using the GET https://api.elevenlabs.io/v1/history endpoint.
	HistoryItemIds []string `json:"history_item_ids"`
}

// BodyEditVoiceV1VoicesVoiceIdEditPost defines model for Body_Edit_voice_v1_voices__voice_id__edit_post.
type BodyEditVoiceV1VoicesVoiceIdEditPost struct {
	// Description How would you describe the voice?
	Description *string `json:"description,omitempty"`

	// Files Audio files to add to the voice
	Files *[]openapi_types.File `json:"files,omitempty"`

	// Labels Serialized labels dictionary for the voice.
	Labels *string `json:"labels,omitempty"`

	// Name The name that identifies this voice. This will be displayed in the dropdown of the website.
	Name string `json:"name"`
}

// BodyTextToSpeechV1TextToSpeechVoiceIdPost defines model for Body_Text_to_speech_v1_text_to_speech__voice_id__post.
type BodyTextToSpeechV1TextToSpeechVoiceIdPost struct {
	// ModelId Identifier of the model that will be used, you can query them using GET /v1/models.
	ModelId *string `json:"model_id,omitempty"`

	// Text The text that will get converted into speech.
	Text string `json:"text"`

	// VoiceSettings Voice settings overriding stored setttings for the given voice. They are applied only on the given TTS request.
	VoiceSettings *VoiceSettingsResponseModel `json:"voice_settings,omitempty"`
}

// BodyTextToSpeechV1TextToSpeechVoiceIdStreamPost defines model for Body_Text_to_speech_v1_text_to_speech__voice_id__stream_post.
type BodyTextToSpeechV1TextToSpeechVoiceIdStreamPost struct {
	// ModelId Identifier of the model that will be used, you can query them using GET /v1/models.
	ModelId *string `json:"model_id,omitempty"`

	// Text The text that will get converted into speech.
	Text string `json:"text"`

	// VoiceSettings Voice settings overriding stored setttings for the given voice. They are applied only on the given TTS request.
	VoiceSettings *VoiceSettingsResponseModel `json:"voice_settings,omitempty"`
}

// ExtendedSubscriptionResponseModel defines model for ExtendedSubscriptionResponseModel.
type ExtendedSubscriptionResponseModel struct {
	AllowedToExtendCharacterLimit  bool                                      `json:"allowed_to_extend_character_limit"`
	CanExtendCharacterLimit        bool                                      `json:"can_extend_character_limit"`
	CanExtendVoiceLimit            bool                                      `json:"can_extend_voice_limit"`
	CanUseInstantVoiceCloning      bool                                      `json:"can_use_instant_voice_cloning"`
	CanUseProfessionalVoiceCloning bool                                      `json:"can_use_professional_voice_cloning"`
	CharacterCount                 int                                       `json:"character_count"`
	CharacterLimit                 int                                       `json:"character_limit"`
	Currency                       ExtendedSubscriptionResponseModelCurrency `json:"currency"`
	HasOpenInvoices                bool                                      `json:"has_open_invoices"`
	NextCharacterCountResetUnix    int                                       `json:"next_character_count_reset_unix"`
	NextInvoice                    InvoiceResponseModel                      `json:"next_invoice"`
	ProfessionalVoiceLimit         int                                       `json:"professional_voice_limit"`
	Status                         ExtendedSubscriptionResponseModelStatus   `json:"status"`
	Tier                           string                                    `json:"tier"`
	VoiceLimit                     int                                       `json:"voice_limit"`
}

// ExtendedSubscriptionResponseModelCurrency defines model for ExtendedSubscriptionResponseModel.Currency.
type ExtendedSubscriptionResponseModelCurrency string

// ExtendedSubscriptionResponseModelStatus defines model for ExtendedSubscriptionResponseModel.Status.
type ExtendedSubscriptionResponseModelStatus string

// FeedbackResponseModel defines model for FeedbackResponseModel.
type FeedbackResponseModel struct {
	AudioQuality    bool    `json:"audio_quality"`
	Emotions        bool    `json:"emotions"`
	Feedback        string  `json:"feedback"`
	Glitches        bool    `json:"glitches"`
	InaccurateClone bool    `json:"inaccurate_clone"`
	Other           bool    `json:"other"`
	ReviewStatus    *string `json:"review_status,omitempty"`
	ThumbsUp        bool    `json:"thumbs_up"`
}

// FineTuningResponseModel defines model for FineTuningResponseModel.
type FineTuningResponseModel struct {
	FineTuningRequested       bool                                   `json:"fine_tuning_requested"`
	FinetuningState           FineTuningResponseModelFinetuningState `json:"finetuning_state"`
	IsAllowedToFineTune       bool                                   `json:"is_allowed_to_fine_tune"`
	Language                  string                                 `json:"language"`
	ModelId                   string                                 `json:"model_id"`
	SliceIds                  []string                               `json:"slice_ids"`
	VerificationAttempts      []VerificationAttemptResponseModel     `json:"verification_attempts"`
	VerificationAttemptsCount int                                    `json:"verification_attempts_count"`
	VerificationFailures      []string                               `json:"verification_failures"`
}

// FineTuningResponseModelFinetuningState defines model for FineTuningResponseModel.FinetuningState.
type FineTuningResponseModelFinetuningState string

// GetHistoryResponseModel defines model for GetHistoryResponseModel.
type GetHistoryResponseModel struct {
	HasMore           bool                       `json:"has_more"`
	History           []HistoryItemResponseModel `json:"history"`
	LastHistoryItemId string                     `json:"last_history_item_id"`
}

// GetVoicesResponseModel defines model for GetVoicesResponseModel.
type GetVoicesResponseModel struct {
	Voices []VoiceResponseModel `json:"voices"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// HistoryItemResponseModel defines model for HistoryItemResponseModel.
type HistoryItemResponseModel struct {
	CharacterCountChangeFrom int                           `json:"character_count_change_from"`
	CharacterCountChangeTo   int                           `json:"character_count_change_to"`
	ContentType              string                        `json:"content_type"`
	DateUnix                 int                           `json:"date_unix"`
	Feedback                 FeedbackResponseModel         `json:"feedback"`
	HistoryItemId            string                        `json:"history_item_id"`
	RequestId                string                        `json:"request_id"`
	Settings                 map[string]interface{}        `json:"settings"`
	State                    HistoryItemResponseModelState `json:"state"`
	Text                     string                        `json:"text"`
	VoiceId                  string                        `json:"voice_id"`
	VoiceName                string                        `json:"voice_name"`
}

// HistoryItemResponseModelState defines model for HistoryItemResponseModel.State.
type HistoryItemResponseModelState string

// InvoiceResponseModel defines model for InvoiceResponseModel.
type InvoiceResponseModel struct {
	AmountDueCents         int `json:"amount_due_cents"`
	NextPaymentAttemptUnix int `json:"next_payment_attempt_unix"`
}

// LanguageResponseModel defines model for LanguageResponseModel.
type LanguageResponseModel struct {
	LanguageId string `json:"language_id"`
	Name       string `json:"name"`
}

// ModelResponseModel defines model for ModelResponseModel.
type ModelResponseModel struct {
	CanBeFinetuned       bool                    `json:"can_be_finetuned"`
	CanDoTextToSpeech    bool                    `json:"can_do_text_to_speech"`
	CanDoVoiceConversion bool                    `json:"can_do_voice_conversion"`
	Description          string                  `json:"description"`
	Languages            []LanguageResponseModel `json:"languages"`
	ModelId              string                  `json:"model_id"`
	Name                 string                  `json:"name"`
	TokenCostFactor      float32                 `json:"token_cost_factor"`
}

// RecordingResponseModel defines model for RecordingResponseModel.
type RecordingResponseModel struct {
	MimeType       string `json:"mime_type"`
	RecordingId    string `json:"recording_id"`
	SizeBytes      int    `json:"size_bytes"`
	Transcription  string `json:"transcription"`
	UploadDateUnix int    `json:"upload_date_unix"`
}

// SampleResponseModel defines model for SampleResponseModel.
type SampleResponseModel struct {
	FileName  string `json:"file_name"`
	Hash      string `json:"hash"`
	MimeType  string `json:"mime_type"`
	SampleId  string `json:"sample_id"`
	SizeBytes int    `json:"size_bytes"`
}

// SubscriptionResponseModel defines model for SubscriptionResponseModel.
type SubscriptionResponseModel struct {
	AllowedToExtendCharacterLimit  bool                              `json:"allowed_to_extend_character_limit"`
	CanExtendCharacterLimit        bool                              `json:"can_extend_character_limit"`
	CanExtendVoiceLimit            bool                              `json:"can_extend_voice_limit"`
	CanUseInstantVoiceCloning      bool                              `json:"can_use_instant_voice_cloning"`
	CanUseProfessionalVoiceCloning bool                              `json:"can_use_professional_voice_cloning"`
	CharacterCount                 int                               `json:"character_count"`
	CharacterLimit                 int                               `json:"character_limit"`
	Currency                       SubscriptionResponseModelCurrency `json:"currency"`
	NextCharacterCountResetUnix    int                               `json:"next_character_count_reset_unix"`
	ProfessionalVoiceLimit         int                               `json:"professional_voice_limit"`
	Status                         SubscriptionResponseModelStatus   `json:"status"`
	Tier                           string                            `json:"tier"`
	VoiceLimit                     int                               `json:"voice_limit"`
}

// SubscriptionResponseModelCurrency defines model for SubscriptionResponseModel.Currency.
type SubscriptionResponseModelCurrency string

// SubscriptionResponseModelStatus defines model for SubscriptionResponseModel.Status.
type SubscriptionResponseModelStatus string

// UserResponseModel defines model for UserResponseModel.
type UserResponseModel struct {
	CanUseDelayedPaymentMethods bool                      `json:"can_use_delayed_payment_methods"`
	IsNewUser                   bool                      `json:"is_new_user"`
	Subscription                SubscriptionResponseModel `json:"subscription"`
	XiApiKey                    string                    `json:"xi_api_key"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Loc  []ValidationError_Loc_Item `json:"loc"`
	Msg  string                     `json:"msg"`
	Type string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// VerificationAttemptResponseModel defines model for VerificationAttemptResponseModel.
type VerificationAttemptResponseModel struct {
	Accepted            bool                   `json:"accepted"`
	DateUnix            int                    `json:"date_unix"`
	LevenshteinDistance float32                `json:"levenshtein_distance"`
	Recording           RecordingResponseModel `json:"recording"`
	Similarity          float32                `json:"similarity"`
	Text                string                 `json:"text"`
}

// VoiceResponseModel defines model for VoiceResponseModel.
type VoiceResponseModel struct {
	AvailableForTiers []string                   `json:"available_for_tiers"`
	Category          string                     `json:"category"`
	Description       string                     `json:"description"`
	FineTuning        FineTuningResponseModel    `json:"fine_tuning"`
	Labels            map[string]string          `json:"labels"`
	Name              string                     `json:"name"`
	PreviewUrl        string                     `json:"preview_url"`
	Samples           []SampleResponseModel      `json:"samples"`
	Settings          VoiceSettingsResponseModel `json:"settings"`
	Sharing           VoiceSharingResponseModel  `json:"sharing"`
	VoiceId           string                     `json:"voice_id"`
}

// VoiceSettingsResponseModel defines model for VoiceSettingsResponseModel.
type VoiceSettingsResponseModel struct {
	SimilarityBoost float32 `json:"similarity_boost"`
	Stability       float32 `json:"stability"`
}

// VoiceSharingResponseModel defines model for VoiceSharingResponseModel.
type VoiceSharingResponseModel struct {
	ClonedByCount       int    `json:"cloned_by_count"`
	HistoryItemSampleId string `json:"history_item_sample_id"`
	LikedByCount        int    `json:"liked_by_count"`
	OriginalVoiceId     string `json:"original_voice_id"`
	PublicOwnerId       string `json:"public_owner_id"`
	Status              string `json:"status"`
}

// GetGeneratedItemsV1HistoryGetParams defines parameters for GetGeneratedItemsV1HistoryGet.
type GetGeneratedItemsV1HistoryGetParams struct {
	// PageSize How many history items to return at maximum. Can not exceed 1000, defaults to 100.
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`

	// StartAfterHistoryItemId After which history_item_id to start fetching, use this parameter to paginate across a large collection of history items. In case this parameter is not provided history items will be fetched starting from the most recently created one ordered descending by their creation date.
	StartAfterHistoryItemId *string `form:"start_after_history_item_id,omitempty" json:"start_after_history_item_id,omitempty"`

	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// DownloadHistoryItemsV1HistoryDownloadPostParams defines parameters for DownloadHistoryItemsV1HistoryDownloadPost.
type DownloadHistoryItemsV1HistoryDownloadPostParams struct {
	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// DeleteHistoryItemV1HistoryHistoryItemIdDeleteParams defines parameters for DeleteHistoryItemV1HistoryHistoryItemIdDelete.
type DeleteHistoryItemV1HistoryHistoryItemIdDeleteParams struct {
	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// GetHistoryItemByIDV1HistoryHistoryItemIdGetParams defines parameters for GetHistoryItemByIDV1HistoryHistoryItemIdGet.
type GetHistoryItemByIDV1HistoryHistoryItemIdGetParams struct {
	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// GetAudioFromHistoryItemV1HistoryHistoryItemIdAudioGetParams defines parameters for GetAudioFromHistoryItemV1HistoryHistoryItemIdAudioGet.
type GetAudioFromHistoryItemV1HistoryHistoryItemIdAudioGetParams struct {
	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// GetModelsV1ModelsGetParams defines parameters for GetModelsV1ModelsGet.
type GetModelsV1ModelsGetParams struct {
	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// TextToSpeechV1TextToSpeechVoiceIdPostParams defines parameters for TextToSpeechV1TextToSpeechVoiceIdPost.
type TextToSpeechV1TextToSpeechVoiceIdPostParams struct {
	// OptimizeStreamingLatency You can turn on latency optimizations at some cost of quality. The best possible final latency varies by model. Possible values:
	// 0 - default mode (no latency optimizations)
	// 1 - normal latency optimizations (about 50% of possible latency improvement of option 3)
	// 2 - strong latency optimizations (about 75% of possible latency improvement of option 3)
	// 3 - max latency optimizations
	// 4 - max latency optimizations, but also with text normalizer turned off for even more latency savings (best latency, but can mispronounce eg numbers and dates).
	OptimizeStreamingLatency *int `form:"optimize_streaming_latency,omitempty" json:"optimize_streaming_latency,omitempty"`

	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// TextToSpeechV1TextToSpeechVoiceIdStreamPostParams defines parameters for TextToSpeechV1TextToSpeechVoiceIdStreamPost.
type TextToSpeechV1TextToSpeechVoiceIdStreamPostParams struct {
	// OptimizeStreamingLatency You can turn on latency optimizations at some cost of quality. The best possible final latency varies by model. Possible values:
	// 0 - default mode (no latency optimizations)
	// 1 - normal latency optimizations (about 50% of possible latency improvement of option 3)
	// 2 - strong latency optimizations (about 75% of possible latency improvement of option 3)
	// 3 - max latency optimizations
	// 4 - max latency optimizations, but also with text normalizer turned off for even more latency savings (best latency, but can mispronounce eg numbers and dates).
	OptimizeStreamingLatency *int `form:"optimize_streaming_latency,omitempty" json:"optimize_streaming_latency,omitempty"`

	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// GetUserInfoV1UserGetParams defines parameters for GetUserInfoV1UserGet.
type GetUserInfoV1UserGetParams struct {
	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// GetUserSubscriptionInfoV1UserSubscriptionGetParams defines parameters for GetUserSubscriptionInfoV1UserSubscriptionGet.
type GetUserSubscriptionInfoV1UserSubscriptionGetParams struct {
	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// GetVoicesV1VoicesGetParams defines parameters for GetVoicesV1VoicesGet.
type GetVoicesV1VoicesGetParams struct {
	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// AddVoiceV1VoicesAddPostParams defines parameters for AddVoiceV1VoicesAddPost.
type AddVoiceV1VoicesAddPostParams struct {
	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// DeleteVoiceV1VoicesVoiceIdDeleteParams defines parameters for DeleteVoiceV1VoicesVoiceIdDelete.
type DeleteVoiceV1VoicesVoiceIdDeleteParams struct {
	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// GetVoiceV1VoicesVoiceIdGetParams defines parameters for GetVoiceV1VoicesVoiceIdGet.
type GetVoiceV1VoicesVoiceIdGetParams struct {
	// WithSettings If set will return settings information corresponding to the voice, requires authorization.
	WithSettings *bool `form:"with_settings,omitempty" json:"with_settings,omitempty"`

	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// EditVoiceV1VoicesVoiceIdEditPostParams defines parameters for EditVoiceV1VoicesVoiceIdEditPost.
type EditVoiceV1VoicesVoiceIdEditPostParams struct {
	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// DeleteSampleV1VoicesVoiceIdSamplesSampleIdDeleteParams defines parameters for DeleteSampleV1VoicesVoiceIdSamplesSampleIdDelete.
type DeleteSampleV1VoicesVoiceIdSamplesSampleIdDeleteParams struct {
	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// GetAudioFromSampleV1VoicesVoiceIdSamplesSampleIdAudioGetParams defines parameters for GetAudioFromSampleV1VoicesVoiceIdSamplesSampleIdAudioGet.
type GetAudioFromSampleV1VoicesVoiceIdSamplesSampleIdAudioGetParams struct {
	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// GetVoiceSettingsV1VoicesVoiceIdSettingsGetParams defines parameters for GetVoiceSettingsV1VoicesVoiceIdSettingsGet.
type GetVoiceSettingsV1VoicesVoiceIdSettingsGetParams struct {
	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// EditVoiceSettingsV1VoicesVoiceIdSettingsEditPostJSONBody defines parameters for EditVoiceSettingsV1VoicesVoiceIdSettingsEditPost.
type EditVoiceSettingsV1VoicesVoiceIdSettingsEditPostJSONBody = VoiceSettingsResponseModel

// EditVoiceSettingsV1VoicesVoiceIdSettingsEditPostParams defines parameters for EditVoiceSettingsV1VoicesVoiceIdSettingsEditPost.
type EditVoiceSettingsV1VoicesVoiceIdSettingsEditPostParams struct {
	// XiApiKey Your API key. This is required by most endpoints to access our API programatically. You can view your xi-api-key using the 'Profile' tab on the website.
	XiApiKey *string `json:"xi-api-key,omitempty"`
}

// DownloadHistoryItemsV1HistoryDownloadPostJSONRequestBody defines body for DownloadHistoryItemsV1HistoryDownloadPost for application/json ContentType.
type DownloadHistoryItemsV1HistoryDownloadPostJSONRequestBody = BodyDownloadHistoryItemsV1HistoryDownloadPost

// TextToSpeechV1TextToSpeechVoiceIdPostJSONRequestBody defines body for TextToSpeechV1TextToSpeechVoiceIdPost for application/json ContentType.
type TextToSpeechV1TextToSpeechVoiceIdPostJSONRequestBody = BodyTextToSpeechV1TextToSpeechVoiceIdPost

// TextToSpeechV1TextToSpeechVoiceIdStreamPostJSONRequestBody defines body for TextToSpeechV1TextToSpeechVoiceIdStreamPost for application/json ContentType.
type TextToSpeechV1TextToSpeechVoiceIdStreamPostJSONRequestBody = BodyTextToSpeechV1TextToSpeechVoiceIdStreamPost

// AddVoiceV1VoicesAddPostMultipartRequestBody defines body for AddVoiceV1VoicesAddPost for multipart/form-data ContentType.
type AddVoiceV1VoicesAddPostMultipartRequestBody = BodyAddVoiceV1VoicesAddPost

// EditVoiceV1VoicesVoiceIdEditPostMultipartRequestBody defines body for EditVoiceV1VoicesVoiceIdEditPost for multipart/form-data ContentType.
type EditVoiceV1VoicesVoiceIdEditPostMultipartRequestBody = BodyEditVoiceV1VoicesVoiceIdEditPost

// EditVoiceSettingsV1VoicesVoiceIdSettingsEditPostJSONRequestBody defines body for EditVoiceSettingsV1VoicesVoiceIdSettingsEditPost for application/json ContentType.
type EditVoiceSettingsV1VoicesVoiceIdSettingsEditPostJSONRequestBody = EditVoiceSettingsV1VoicesVoiceIdSettingsEditPostJSONBody

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
